import os
import ast

env_path = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
    "gymnasium_robotics",
    "envs",
    "multiagent_mujoco"
)

for file in os.listdir(env_path):
    if file.endswith(".py") and file != "__init__.py" and file != 'mamujoco_v0.py':
        file_path = os.path.join(env_path, file)
        file_name = file.split(".")[0]
        file_contents = ""

        with open(file_path) as fd:
            file_contents = fd.read()
        module = ast.parse(file_contents)
        docstring = ast.get_docstring(module)
        if docstring is None:
            docstring = ""

        # getting docstrings from classes and functions
        for node in ast.walk(module):
            if isinstance(node, ast.ClassDef):
                if ast.get_docstring(node) is not None:
                    docstring += ast.get_docstring(node)
                for child in ast.walk(node):
                    if isinstance(child, ast.FunctionDef):
                        if ast.get_docstring(child) is not None:
                            docstring += ast.get_docstring(child)


        # output path
        output_path = os.path.join(
            os.path.dirname(os.path.dirname(__file__)),
            "envs",
            "MaMuJoCo",
            f"{file_name}.md",
        )

        front_matter = f"""---
autogenerated:
title: {file_name}
---
"""
        title = f"# {file_name}"

        if docstring is None or docstring == "":
            docstring = "No information provided"
        all_text = f"""{front_matter}
    {docstring}
    """
        file = open(output_path, "w+", encoding="utf-8")
        file.write(all_text)
        file.close()
